version: '2'
volumes:
    resin-data:
services:
    plex:
        build: ./plex
        privileged: true
        network_mode: host
        volumes:
          - 'resin-data:/data'
        ports:
          - "32400:32400/tcp"
          - "1900:1900/udp"
          - "32410:32410/udp"
          - "32412:32412/udp"
          - "32413:32413/udp"
          - "32414:32414/udp"
          - "32469:32469/tcp"
